apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: jenkins
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  DOCKERHUB_USERNAME: eW91cmRvY2tlcmh1Yg==  # yourdockerhub
  DOCKERHUB_PASSWORD: eW91cnBhc3N3b3Jk      # yourpassword
  GITHUB_USERNAME: eW91cmdpdGh1Yg==          # yourgithub
  GITHUB_TOKEN: Z2hwX3Rva2Vu              # ghp_token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically"
      numExecutors: 2
    credentials:
      system:
        domainCredentials:
        - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-credentials"
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_PASSWORD}"
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_TOKEN}"